server:
  servlet:
    context-path: /stream

spring:
  datasource:
    url:  jdbc:h2:./stream
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
  main:
    allow-circular-references: true

  sql:
    init:
      mode: never