INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Thriller');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'The Dark Side of the Moon');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'El guardaespaldas');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Back in Black');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Bat out of Hell');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Their Greatest Hits');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Come On Over');
INSERT INTO ALBUMS (id,title) VALUES (NEXT VALUE FOR ALBUM_SEQUENCE,'Fiebre del sábado noche');

INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Lucas');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Carlos');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Alejandro');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Shakira');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Elvis Presley');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Tina Turner');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Madonna');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Eminem');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Michael Jackson');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Lady Gaga');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Elton John');
INSERT INTO ARTISTS (id,name) VALUES (NEXT VALUE FOR ARTIST_SEQUENCE,'Taylos Swift');

INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Pop');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Blues');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Jazz');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Rock');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Metal');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Country');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Funk');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Techno');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Flamenco');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'Salsa');
INSERT INTO STYLES (id,name) VALUES (NEXT VALUE FOR STYLE_SEQUENCE,'HipHop');

